title: Manoa Lost and Found
description: A platform that connects students of UH Manoa with each other to find lost and found items.
google_analytics:
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
